spring:
  datasource:
    url: jdbc:mysql://47.94.99.133:3306/Database?serverTimezone=GMT%2B8&useAffectedRows=true
    username: root
    password: Word123456.
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:com/example/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8081